name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Bundler
      run: gem install bundler -v 2.4.22

    - name: Install dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install

    - name: Set up API Key
      run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

    - name: Run tests
      run: |
        bundle exec ruby main.rb
        echo "GitHub Repository URL: https://github.com/${{ github.repository }}"
